### PR TITLE
Added new plugin for text-decoration-skip-ink property

### PR DESCRIPTION
**Pull request by AleshaOleg**

### CODE REVIEW

**Comment by kof** [comment]
Test failed, is the test wrong or the code?

**Comment by AleshaOleg** [comment]
@kof actually code is wrong :( I thought `-webkit-` prefix will work for both cases (Safari and Chrome). But according to autoprefixer, Chrome don't need prefix and Safari requires it. Don't know for now how to deal with it

**Comment by kof** [comment]
```
'-apple-trailing-word' in document.createElement('p').style
```

works

**Comment by kof** [comment]
since you are not detecting safari, you are detecting apple as a vendor, mb better to call it `vendor` and 'apple' as a value

**Comment by kof** [comment]
I mean potentially it could be other browser using webkit fork with this apple specific property

**Comment by AleshaOleg** [comment]
Just pushed updates

**Comment by AleshaOleg** [comment]
@kof could you please check it again? I pushed required changes

**Pull request merged**
