### PR TITLE
Fix for writing mode

### PR DESCRIPTION
**Pull request by AleshaOleg**

### CODE REVIEW

**Comment by kof** [comment]
Not sure what this does, but if this way we pass the tests, I don't care)

**Comment by AleshaOleg** [comment]
@kof it's just a check, locally tests runs too long. I just make a pr, to check if it breaks in old browsers. If not, it helps to support newest Safari

**Comment by kof** [comment]
Seems to work, merging?

**Comment by AleshaOleg** [comment]
@kof yes

**Comment by kof** [comment]
merged!

**Pull request merged**
